# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/artyo/Desktop/Vivado/MicroBlaze_demo/MicroBlaze_demo.srcs/sources_1/bd/MicroBlaze_design/ip/MicroBlaze_design_ilmb_bram_if_cntlr_0/MicroBlaze_design_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'MicroBlaze_design_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/artyo/Desktop/Vivado/MicroBlaze_demo/MicroBlaze_demo.gen/sources_1/bd/MicroBlaze_design/ip/MicroBlaze_design_ilmb_bram_if_cntlr_0/MicroBlaze_design_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_design_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/artyo/Desktop/Vivado/MicroBlaze_demo/MicroBlaze_demo.srcs/sources_1/bd/MicroBlaze_design/ip/MicroBlaze_design_ilmb_bram_if_cntlr_0/MicroBlaze_design_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'MicroBlaze_design_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/artyo/Desktop/Vivado/MicroBlaze_demo/MicroBlaze_demo.gen/sources_1/bd/MicroBlaze_design/ip/MicroBlaze_design_ilmb_bram_if_cntlr_0/MicroBlaze_design_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_design_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
