# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3_master.xdc

# Block Designs: bd/MicroBlaze_design/MicroBlaze_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design || ORIG_REF_NAME==MicroBlaze_design} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_clk_wiz_0_0/MicroBlaze_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_clk_wiz_0_0 || ORIG_REF_NAME==MicroBlaze_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_microblaze_0_0/MicroBlaze_design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_microblaze_0_0 || ORIG_REF_NAME==MicroBlaze_design_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_dlmb_v10_0/MicroBlaze_design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_dlmb_v10_0 || ORIG_REF_NAME==MicroBlaze_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_ilmb_v10_0/MicroBlaze_design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_ilmb_v10_0 || ORIG_REF_NAME==MicroBlaze_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_dlmb_bram_if_cntlr_0/MicroBlaze_design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlaze_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_ilmb_bram_if_cntlr_0/MicroBlaze_design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlaze_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_lmb_bram_0/MicroBlaze_design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_lmb_bram_0 || ORIG_REF_NAME==MicroBlaze_design_lmb_bram_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_xbar_0/MicroBlaze_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_xbar_0 || ORIG_REF_NAME==MicroBlaze_design_xbar_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_microblaze_0_axi_periph_0/MicroBlaze_design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroBlaze_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_microblaze_0_axi_intc_0/MicroBlaze_design_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MicroBlaze_design_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_microblaze_0_xlconcat_0/MicroBlaze_design_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MicroBlaze_design_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_mdm_1_0/MicroBlaze_design_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_mdm_1_0 || ORIG_REF_NAME==MicroBlaze_design_mdm_1_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_rst_clk_wiz_0_100M_0/MicroBlaze_design_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==MicroBlaze_design_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_axi_uartlite_0_0/MicroBlaze_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlaze_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_design/ip/MicroBlaze_design_axi_gpio_0_0/MicroBlaze_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlaze_design_axi_gpio_0_0 || ORIG_REF_NAME==MicroBlaze_design_axi_gpio_0_0} -quiet] -quiet

# XDC: c:/Users/artyo/Desktop/Vivado/MicroBlaze_demo/MicroBlaze_demo.gen/sources_1/bd/MicroBlaze_design/MicroBlaze_design_ooc.xdc
